const types = [
  'floatFromBottomBig',
  'floatFromBottom',
  'floatFromTop',
  'floatFromLeft',
  'floatFromRight',
  'scale',
  'opacity',
  'fadeIn',
  'fadeInDown',
  'fadeInLeft',
  'fadeInRight',
  'fadeInUp',
  'slideInUp',
  'slideInDown',
  'slideInLeft',
  'slideInRight',
  'zoomIn',
  'zoomDownIn',
  'zoomUpIn',
  'zoomInRight',
  'zoomInLeft',
];

export default types;